language: android
jdk: oraclejdk8
dist: xenial # 16.04 LTS (Xenial Xerus)

android:
  components:
    - build-tools-29.0.0
    - android-29
    - sys-img-armeabi-v7a-android-26

env:
  global:
    - ANDROID_NDK_ROOT=$ANDROID_HOME/ndk-bundle
    - ANDROID_NDK_HOME=$ANDROID_NDK_ROOT
    - GRADLE_USER_HOME=$HOME/.gradle

before_cache:
  # (see https://docs.travis-ci.com/user/languages/java/#Caching)
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/android-sdk
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache # (see http://tools.android.com/tech-docs/build-cache)

install:
    - echo y | sdkmanager "ndk-bundle"
    - echo y | sdkmanager "ndk;20.1.5948944"
    - echo y | sdkmanager "cmake;3.6.4111459"
    - echo y | sdkmanager "cmake;3.10.2.4988404"

script: ./gradlew --no-daemon --parallel lintDebug testDebug
