name: Continuous integration

on:
  push:
    branches:
      - docker

jobs:
  build:
    runs-on: ubuntu-latest
    container: 
      image: cimg/android:2021.08.1
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v2
      - name: Checkout
        run: mkdir ~/temp
        
      - name: Copy CI gradle.properties
        run: mkdir -p ~/.gradle ; cp .github/ci-gradle.properties ~/.gradle/gradle.properties

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Cache between builds
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Build project
        run: ./gradlew :app:assembleDebug
